### ISSUE TITLE
WEB - Full App Tests Tracker

### ISSUE THREAD

**Issue by huzaifa-99** [e-Learning-DAO/POCRE#158]
This issue is to track all web app related tests and the valid test cases that should pass. Any new test case discovered or any update to existing test case should happen on this original comment for better tracking.

Below are some test cases that should work.

### Test Cases
<details>
<summary>Creation</summary>

- [ ] 1- A new non-draft creation **without material/s** is created successfully
- [ ] 2- Correct data is displayed for non-draft creation **without material/s** on the creations home page for the creation author
- [ ] 3- Correct data is displayed for non-draft creation **without material/s** on the creations details page for the creation author
- [ ] 4- Correct data is displayed for non-draft creation **without material/s** on the creations details page for a public user
- [ ] 5- A new draft creation **without material/s** is created successfully
- [ ] 6- Correct data is displayed for draft creation **without material/s** on the creations home page for the creation author
- [ ] 7- Correct data is displayed for draft creation **without material/s** on the creations details page for the creation author
- [ ] 8- A public user is not allowed to visit details page for a draft creation until that creation is in draft status
- [ ] 9- A creation author is allowed to edit a draft creation **without material/s**
- [ ] 10- A creation author is allowed to edit a draft creation **with material/s**
- [ ] 11- A draft creation after publishing has correct data on creation home page
- [ ] 11- A draft creation after publishing has correct data on creation details page
- [ ] 12- A creation author is allowed to delete a non-draft creation successfully
- [ ] 13- A creation author is allowed to delete a draft creation successfully
- [ ] 14- A creation author is not allowed to edit a published creation **with or without material/s**
- [ ] 15- A new non-draft creation **with material/s** is created successfully
- [ ] 16- Correct data is displayed for non-draft creation **with material/s** on the creations home page for the creation author
- [ ] 17- Correct data is displayed for non-draft creation **with material/s** on the creations details page for the creation author
- [ ] 18- Correct data is displayed for non-draft creation **with material/s** on the creations details page for a public user
- [ ] 19- A new draft creation **with material/s** is created successfully
- [ ] 20- Correct data is displayed for draft creation **with material/s** on the creations home page for the creation author
- [ ] 21- Correct data is displayed for draft creation **with material/s** on the creations details page for the creation author

</details>

**Comment by huzaifa-99** [comment]
Question: Should a creation author be blocked from deleting a creation, if that creation is in a litigation process?

@AltiMario Is this a valid test case to track and solve?

**Comment by huzaifa-99** [comment]
### Discovered Issues for initial tests

1. Dates are not synced, most dates are appended by a day. (Will create a separate issue for this)

**Comment by AltiMario** [comment]
I did this creation without materials 
https://web-frontend--pocre.netlify.app/creations/87db26b9-7103-4454-8077-7000f841f230
but on clicking on "proof of creation" it shows nonexistent data
![image](https://user-images.githubusercontent.com/598726/204641217-1a3f47e0-7002-429c-903b-9a1217360627.png)

**Comment by AltiMario** [comment]
This simple no-material creation 
![image](https://user-images.githubusercontent.com/598726/204642944-e596e60b-33f8-483b-8d21-ec2565052adf.png)
the source is well displayed (the download button as well) but the link doesn't work properly
![image](https://user-images.githubusercontent.com/598726/204643070-2e540fab-8b38-4e2f-b4d5-c086b1f56000.png)
you can test here https://web-frontend--pocre.netlify.app/creations/87db26b9-7103-4454-8077-7000f841f230

**Comment by huzaifa-99** [comment]
> This simple no-material creation ![image](https://user-images.githubusercontent.com/598726/204642944-e596e60b-33f8-483b-8d21-ec2565052adf.png) the source is well displayed (the download button as well) but the link doesn't work properly ![image](https://user-images.githubusercontent.com/598726/204643070-2e540fab-8b38-4e2f-b4d5-c086b1f56000.png) you can test here https://web-frontend--pocre.netlify.app/creations/87db26b9-7103-4454-8077-7000f841f230

This was relatively simple, added a fix [here](https://github.com/e-Learning-DAO/POCRE/pull/162/commits/2b698e7e9d0c604bd08f98b5c019dba88cc233c8)

**Comment by huzaifa-99** [comment]
> I did this creation without materials https://web-frontend--pocre.netlify.app/creations/87db26b9-7103-4454-8077-7000f841f230 but on clicking on "proof of creation" it shows nonexistent data ![image](https://user-images.githubusercontent.com/598726/204641217-1a3f47e0-7002-429c-903b-9a1217360627.png)

added in original comment as point # 26

**Comment by AltiMario** [comment]
In a creation (like this https://web-frontend--pocre.netlify.app/creations/87db26b9-7103-4454-8077-7000f841f230) without co-authors don't  display avatars
![image](https://user-images.githubusercontent.com/598726/204645962-1267f7d1-745f-40bf-8159-ca83dee17b70.png)

**Comment by huzaifa-99** [comment]
> In a creation (like this https://web-frontend--pocre.netlify.app/creations/87db26b9-7103-4454-8077-7000f841f230) without co-authors don't display avatars ![image](https://user-images.githubusercontent.com/598726/204645962-1267f7d1-745f-40bf-8159-ca83dee17b70.png)

added as point 27

**Comment by AltiMario** [comment]
> Question: Should a creation author be blocked from deleting a creation, if that creation is in a litigation process?
> 
> @AltiMario Is this a valid test case to track and solve?

@huzaifa-99 very good point. It is safe to delete a creation when every ongoing process is completed.

**Comment by huzaifa-99** [comment]
> > Question: Should a creation author be blocked from deleting a creation, if that creation is in a litigation process?
> > @AltiMario Is this a valid test case to track and solve?
> 
> @huzaifa-99 very good point. It is safe to delete a creation when every ongoing process is completed.

I will create a separate issue and add to the comment [here](https://github.com/e-Learning-DAO/POCRE/issues/158#issuecomment-1331220164)

**Comment by AltiMario** [comment]
wrong number of creations displayed in the profile
![image](https://user-images.githubusercontent.com/598726/204671369-efb5bd97-6f28-4437-9cb6-3a61d08e05d2.png)

**Comment by huzaifa-99** [comment]
> > > Question: Should a creation author be blocked from deleting a creation, if that creation is in a litigation process?
> > > @AltiMario Is this a valid test case to track and solve?
> > 
> > 
> > @huzaifa-99 very good point. It is safe to delete a creation when every ongoing process is completed.
> 
> I will create a separate issue and add to the comment [here](https://github.com/e-Learning-DAO/POCRE/issues/158#issuecomment-1331220164)

This was added as point 30 in the [original comment](https://github.com/e-Learning-DAO/POCRE/issues/158#issue-1468607429)

**Comment by AltiMario** [comment]
About #31, I think it is an uncommon use case since we allow the creation without materials. However, looking forward we could in the future allow this workflow extension (not now).

**Comment by AltiMario** [comment]
@huzaifa-99 I agree with you but I would add only the `created_at` field that is good enough for the display ordered by creation.
